### ISSUE TITLE
self-intersecting panels 

### ISSUE THREAD

**Issue by jingfengguo-ai** [maria-korosteleva/Garment-Pattern-Generator#13]
When I get some specification.json, running datasim.py hoping to get 3D Mesh, there is an error when running garment.load() on line 211 of mayaqltools\ simulate.py, do you know how I can check for the error？

*** mayaqltools.mayascene.PatternLoadingError: MayaGarment::WOMEN-Skirts-id_00004507-02_1_front::Provided pattern has self-intersecting panels. Nothing is loaded

**Comment by maria-korosteleva** [comment]
The error means what it says. When some panel's edges intersect, the panel (representing a piece of fabric) is invalid and the geometry of the pattern cannot be generated. Adjust the pattern so that it doesn't have intersecting edges in any of the panels

The check for self-intersection is happening [here](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/6b44100aeee3105709e434364b1a90bd1dea006e/packages/mayaqltools/mayascene.py#L71)

Note that the check for self-intersection is conservative and might indicate self-intersection when some edges have extreme curvature but do not de facto intersect with other edges
