### ISSUE TITLE
Is there any progress or  suggestion on swithcing to Open Source cloth simulator?

### ISSUE THREAD

**Issue by StevenLiuWen** [maria-korosteleva/Garment-Pattern-Generator#4]
Hi, researchers,

Thanks for this nice project to automatically generate the 3d garment dataset. Currently, this project heavily relies on the Maya and Qualoth, which results in a long pipeline from the 2d generated patterns to 3d garments (such as mesh). I wonder if there are any suggestions to make a simple pipeline that the inputs are the 2d patterns and the outputs are the 3d garments in meshes via other alternative open source tools (simulators, etc...). Looking forward to your responses, and thanks in advance.

**Comment by maria-korosteleva** [comment]
Hi @StevenLiuWen 

Thank you so much for your interest in our work! I understand your request, and it would indeed be easier to use our pipeline with open-source libs.

We chose to use commercial tools because they provide a lot of subroutines that otherwise require implementation (e.g. generating meshes from panel curves). We are a university lab and the resources that we can dedicate to development are, unfortunately, quite limited. For the same reason, we do not currently have plans on re-implementing the pipeline, but we would welcome contributions in this direction if the community would like to chime in. 

However, if you are from an educational institution, obtaining the needed software should not be much trouble, since both companies provide educational and research licenses. If you have the licenses, installing the tools and our generator should be fairly straightforward.

**Comment by StevenLiuWen** [comment]
Got it, thanks for your patient reply.
