### ISSUE TITLE
Question about the body model "f_smpl_template_TA_pose.obj"

### ISSUE THREAD

**Issue by liren2515** [maria-korosteleva/Garment-Pattern-Generator#7]
Hello Maria,

I found the number of vertices of f_smpl_template_TA_pose.obj is more than that of smpl model, but the numbers of faces are the same. Could you share with me how you generate this TA model and how I can get the corresponding smpl pose (\theta) parameter for it?

**Comment by maria-korosteleva** [comment]
It's been a while since I experimented with this model, so I cannot say the exact parameters (most likely, some round number for hip joint rotation). It's quite surprising to me too that the number of vertices is different 🤔

This model was not used in our paper nor our dataset, so if you need something similar, I don't see any reason why it has to be an exact copy of the one provided with our code. I think the most convenient for you would be to sample this kind of pose from SMPL model yourself =) Then you will get the correct vertices and the exact pose parameters.

**Comment by liren2515** [comment]
Thanks for your quick response! I think I have gotten the approximated parameters.
