### ISSUE TITLE
Qualoth With GUI for Maya or Without GUI for Maya

### ISSUE THREAD

**Issue by sh-taheri** [maria-korosteleva/Garment-Pattern-Generator#8]
Thanks a lot for the great work, I have so far tried your "Garment Pattern Estimation" and it is quite impressive. 

I am planning to purchase the "Qualoth" software academic license as it is a requirement currently, however, there are two options: 
"With GUI for Maya" and "Without GUI for Maya". Can you please advise if the "With GUI for Maya" option is needed? 

Thanks!

<img width="712" alt="Qualoth_version" src="https://user-images.githubusercontent.com/30083143/225964019-91655cb1-607a-45c3-a95e-13275cb23544.png">

**Comment by maria-korosteleva** [comment]
Sure! Thank you for your interest in our project ^_^

You will need a GUI Option if you want to play with our Garment Viewer GUI since you must load Maya with GUI.
If you only need the license for dataset generation the batch (no GUI) will suffice.
 
I think I would have 1 GUI license (to debug and visualize garment templates) and a few batch licenses to parallelize generation.

**Comment by sh-taheri** [comment]
Thanks a lot for your quick response :)
